/*****************************************************************************/
/* <auto-generated>                                                          */
/*   This file was generated by CatppuccinGenerator.                         */
/*                                                                           */
/*   Changes to this file may cause incorrect behavior and will be lost if   */
/*   the code is regenerated.                                                */
/* </auto-generated>                                                         */
/*****************************************************************************/

namespace Catppuccin {
  /// <summary>
  /// A Catppuccin palette.json ANSI color pair.
  /// </summary>
  public class AnsiColorPair {
    /// <summary>
    /// The normal (non-bright) ANSI color.
    /// </summary>
    public required Color Normal { get; set; }

    /// <summary>
    /// The bright ANSI color.
    /// </summary>
    public required Color Bright { get; set; }
  }
}