/*****************************************************************************/
/* <auto-generated>                                                          */
/*   This file was generated by CatppuccinGenerator.                         */
/*                                                                           */
/*   Changes to this file may cause incorrect behavior and will be lost if   */
/*   the code is regenerated.                                                */
/* </auto-generated>                                                         */
/*****************************************************************************/

namespace Catppuccin {
  /// <summary>
  /// Catppuccin colors.
  /// </summary>
  public enum ColorEnum {
    Rosewater,
    Flamingo,
    Pink,
    Mauve,
    Red,
    Maroon,
    Peach,
    Yellow,
    Green,
    Teal,
    Sky,
    Sapphire,
    Blue,
    Lavender,
    Text,
    Subtext1,
    Subtext0,
    Overlay2,
    Overlay1,
    Overlay0,
    Surface2,
    Surface1,
    Surface0,
    Base,
    Mantle,
    Crust
  }
}