/*****************************************************************************/
/* <auto-generated>                                                          */
/*   This file was generated by CatppuccinGenerator.                         */
/*                                                                           */
/*   Changes to this file may cause incorrect behavior and will be lost if   */
/*   the code is regenerated.                                                */
/* </auto-generated>                                                         */
/*****************************************************************************/

namespace Spakov.Catppuccin
{
    /// <summary>
    /// A Catppuccin palette.json flavor.
    /// </summary>
    public class Flavor
    {
        /// <summary>
        /// Flavor colors.
        /// </summary>
        public required Colors Colors { get; set; }

        /// <summary>
        /// Flavor ANSI colors.
        /// </summary>
        public required AnsiColors AnsiColors { get; set; }
    }
}