/*****************************************************************************/
/* <auto-generated>                                                          */
/*   This file was generated by CatppuccinGenerator.                         */
/*                                                                           */
/*   Changes to this file may cause incorrect behavior and will be lost if   */
/*   the code is regenerated.                                                */
/* </auto-generated>                                                         */
/*****************************************************************************/

namespace Catppuccin {
  /// <summary>
  /// Catppuccin flavors.
  /// </summary>
  public enum FlavorEnum {
    Latte,
    Frappe,
    Macchiato,
    Mocha
  }
}