/*****************************************************************************/
/* <auto-generated>                                                          */
/*   This file was generated by CatppuccinGenerator.                         */
/*                                                                           */
/*   Changes to this file may cause incorrect behavior and will be lost if   */
/*   the code is regenerated.                                                */
/* </auto-generated>                                                         */
/*****************************************************************************/

namespace Spakov.Catppuccin {
  /// <summary>
  /// A Catppuccin flavor color rgb object in palette.json.
  /// </summary>
  public class Rgb {
    /// <summary>
    /// The red component.
    /// </summary>
    public required int Red { get; set; }

    /// <summary>
    /// The green component.
    /// </summary>
    public required int Green { get; set; }

    /// <summary>
    /// The blue component.
    /// </summary>
    public required int Blue { get; set; }
  }
}