name: TermBar Integration

on:
  pull_request:
    branches: [ "main", "release/v*" ]

jobs:
  build:
    strategy:
      matrix:
        platform: [x64, ARM64]
        configuration: [Release]
        include:
          - platform: x64
            runs-on: windows-latest
          - platform: ARM64
            runs-on: windows-11-arm

    uses: ./.github/workflows/build.yml

    with:
      runs-on: ${{ matrix.runs-on }}
      platform: ${{ matrix.platform }}
      configuration: ${{ matrix.configuration }}

    secrets:
      TERMBAR_CERTIFICATE: ${{ secrets.TERMBAR_CERTIFICATE }}
